name: 'Melon Ticket Notifier'
description: 'GitHub action that notifies ticket availability'
author: 'MooYeol Prescott Lee'
inputs:
  product-id:
    description: '211517'
    required: true
  schedule-id:
    description: '100002'
    required: true
  seat-id:
    description: '1_0'
    required: true
  slack-incoming-webhook-url:
    description: 'https://hooks.slack.com/services/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'
    required: true
  message:
    description: 'Message'
    required: false
    default: '티켓사세요'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'music'
  color: 'green'
